from django.urls import path
# from .views import home, signup, user_login, user_logout
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', views.user_login, name='login'),
    path('logout/', views.user_logout, name='logout'),
    path('forgot_password/', views.forgot_password, name='forgot_password'),
    path('reset_password/<str:token>/', views.reset_password, name='reset_password'),
    path('google/login/', views.google_login, name='google_login'),
    path('google/callback/', views.google_callback, name='google_callback'),
    path('github/login/', views.github_login, name='github_login'),
    path('github/callback/', views.github_callback, name='github_callback'),
    path('privacy_policy/', views.privacy_policy, name='privacy_policy'),
    path('terms_and_conditions/', views.terms_and_conditions, name='terms_and_conditions'),
    path('about_us/', views.about_us, name='about_us'),
    path('post/<slug:slug>/', views.post_detail, name='post_detail'),
    path('user/<str:username>/', views.user_profile, name='user_profile'),
    path('toggle_like/<int:post_id>/', views.toggle_like, name='toggle_like'),
    path('follow_unfollow/<str:username>/', views.follow_unfollow, name='follow_unfollow'),
    path('followers/<str:username>/', views.user_followers, name='followers'),
    path('followings/<str:username>/', views.user_followings, name='followings'),
    path('posts/<str:username>/', views.user_posts, name="posts"),
    path('category/<str:category>/', views.category_posts, name="category" ),
    path('tag/<str:tag>/', views.tag_posts, name="tag"),
    path('notifications/', views.notifications, name="notifications"),
    path('mark_read/', views.marks_notifications_read, name="mark_read"),
    path('settings/', views.user_settings, name="settings" ),
    path('update_user_info/', views.update_user_info, name='update_user_info'),
    path('update_profile_banner_image/', views.update_profile_banner_image, name='update_profile_banner_image'),
    path('delete_banner_image/', views.delete_banner_image, name='delete_banner_image'),
    path('delete_profile_image/', views.delete_profile_image, name='delete_profile_image'),
    path('save_social_links/', views.save_social_links, name="save_social_links"),
    path('delete_social_link/<str:linktype>', views.delete_social_link, name="delete_social_link"),
    path('change_password/', views.change_password, name='change_password'),
    path('delete_user/', views.delete_user, name='delete_user'),
    path('search/', views.search, name='search'),
    path('recent-searches/', views.recent_searches, name='recent_searches'),
    path('save-search-query/', views.save_search_query, name='save_search_query'),
    path('delete-search-query/<str:query>/', views.delete_search_query, name='delete_search_query'),
    path('create_post/', views.create_post, name='create_post'),
    path('add_category/', views.add_category, name='add_category'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('update_post/<slug:slug>/', views.update_post, name='update_post'),
    path('delete_post/<slug:slug>/', views.delete_post, name='delete_post'),
    path('user_activity/', views.user_activity, name='user_activity'),
]