# Generated by Django 5.0.3 on 2024-12-09 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_method',
            field=models.CharField(choices=[('default', 'Default'), ('google', 'Google'), ('github', 'GitHub')], default='default', max_length=10),
        ),
    ]
