# Generated by Django 5.0.3 on 2024-12-29 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_alter_post_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='banner_image',
            field=models.ImageField(blank=True, null=True, upload_to='banners/'),
        ),
    ]
