# Generated by Django 5.0.3 on 2025-02-10 12:37

import imagekit.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_alter_notification_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='banners/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
    ]
