# Generated by Django 5.0.3 on 2025-03-02 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0038_activity_linktype_alter_activity_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='linkType',
        ),
    ]
