# Generated by Django 5.0.3 on 2025-02-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0032_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('like', 'Like'), ('comment', 'Comment'), ('reply', 'Reply'), ('reply1', 'Reply1'), ('follow', 'Follow'), ('post', 'Post')], max_length=10),
        ),
    ]
