# Generated by Django 5.0.3 on 2025-03-02 08:34

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0036_searchquery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('post_create', 'Post Created'), ('post_update', 'Post Updated'), ('post_delete', 'Post Deleted'), ('post_like', 'Post Liked'), ('post_unlike', 'Post Unliked'), ('post_comment', 'Post Commented'), ('post_reply', 'Post Replied'), ('follow', 'Followed'), ('unfollow', 'Unfollowed'), ('profile_update', 'Profile Updated'), ('banner_update', 'Banner Updated'), ('user_info_update', 'User Info Updated'), ('password_change', 'Password Changed'), ('social_link_add', 'Social Link Added')], max_length=20)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.comment')),
                ('followed_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='followed_user', to=settings.AUTH_USER_MODEL)),
                ('post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
