# Generated by Django 5.0.3 on 2025-02-02 18:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0028_alter_user_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(choices=[('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('github', 'GitHub'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube'), ('reddit', 'Reddit'), ('pinterest', 'Pinterest'), ('medium', 'Medium'), ('snapchat', 'Snapchat')], max_length=255)),
                ('link_url', models.URLField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
