"""
Django settings for final_project project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-^otu=!fb@y*0i1_zab*&_!94x0$@wk#lw43y2s&k1o%s6q-_=6"

# SECURITY WARNING: don't run with debug turned on in production!
# DEBUG = 'RENDER' not in os.environ
# SECRET_KEY = os.environ.get('SECRET_KEY','dev-secret-key')

DEBUG = True
# SECRET_KEY = os.environ.get('SECRET_KEY', 'dev-secret-key')
ALLOWED_HOSTS = []
# set site id
# SITE_ID = 1 

# Application definition

# Add your GitHub Client ID and Secret
GITHUB_CLIENT_ID = 'Ov23liiNAiIxXnKEkNo7'
GITHUB_CLIENT_SECRET = 'b9c0d1641b50c8ef132e8d2a1152345fdc154b04'

# Add a URL for the callback
GITHUB_CALLBACK_URL = 'http://127.0.0.1:8000/github/callback/'

# Add your Google Client ID and Secret
GOOGLE_CLIENT_ID = "55543214080-93k2v44h75tp0p6l3h55lh0qhs6bgdem.apps.googleusercontent.com"
GOOGLE_CLIENT_SECRET = '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'

# Add a URL for the callback
GOOGLE_CALLBACK_URL = 'http://127.0.0.1:8000/google/callback/'



INSTALLED_APPS = [
    "blog",
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "compressor",
    "tinymce",
    "imagekit",
    'rest_framework',
]

TINYMCE_DEFAULT_CONFIG = {
    'theme': 'silver',
    'height': 300,
    'width': '100%',
    # 'plugins': 'link image code',
    'plugins': [
      'advlist','anchor', 'image media link code', 'autolink', 'charmap', 'codesample', 'emoticons', 'image', 'link', 'lists', 'media', 'searchreplace', 'table', 'visualblocks', 'wordcount',
      'checklist', 'mediaembed', 'casechange', 'export', 'formatpainter', 'pageembed', 'a11ychecker', 'tinymcespellchecker', 'permanentpen', 'powerpaste', 'advtable', 'advcode', 'editimage', 'advtemplate', 'ai', 'mentions', 'tinycomments', 'tableofcontents', 'footnotes', 'mergetags', 'autocorrect', 'typography', 'inlinecss', 'markdown','importword', 'exportword', 'exportpdf','fullscreen', 'print', 'preview', 'insertdatetime', 
    ],
    'toolbar': 'undo redo | blocks fontfamily fontsize | styleselect | bold italic underline backcolor strikethrough | link image media table mergetags | align lineheight | numlist bullist indent outdent | emoticons charmap  | code | removeformat',
    'file_picker_types': 'image', 
    'automatic_uploads':True, 
    'image_upload_url': '/upload_image/',
}


# ALGOLIA = {
#   'APPLICATION_ID': 'BAVC41PT7L',
#   'API_KEY': 'ba3f0bd7fd7f03669571497d8b142ff3'
# }


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    # "allauth.account.middleware.AccountMiddleware",
    # 'social_django.middleware.SocialAuthExceptionMiddleware',
]

ROOT_URLCONF = "final_project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": ["templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "blog.context_processors.layout_processor",  # Add this line
            ],
        },
    },
]

WSGI_APPLICATION = "final_project.wsgi.application"

# Email Backend
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "rohitkrgupta8292@gmail.com"
EMAIL_HOST_PASSWORD = "oujc tyhe koqp fpay"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}

# DATABASES = {
#     'default': dj_database_url.config(conn_max_age=600, ssl_require=True)
# }

AUTH_USER_MODEL = "blog.User"


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

MEDIA_URL = '/media/'
# MEDIA_ROOT = '/opt/render/project/src/media'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / 'staticfiles'
# STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
STATICFILES_DIRS = [BASE_DIR / "static"]
COMPRESS_ROOT = "static"
COMPRESS_ENABLED = True
STATICFILES_FINDERS = ("compressor.finders.CompressorFinder",)

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
